version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=f/oC/p47DC59yKn6gjKUd/GNiSH0aRlam3/Yt7beLws=
      - NEXTAUTH_URL=http://localhost:3000
      - OPENSEARCH_HOST=host.docker.internal
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_PROTOCOL=https
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=password
      - ANNOTATION_INDEX=annotations
      - DATABASE_URL=file:./data/prod.db
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"