name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          # Clone the repository on the EC2 instance if it doesn't exist
          ssh ec2-user@${{ secrets.EC2_HOST }} '
            if [ ! -d "/home/ec2-user/app/.git" ]; then
              cd /home/ec2-user/app
              git clone https://github.com/${{ github.repository }} .
            fi
          '
          
          # Deploy the application
          ssh ec2-user@${{ secrets.EC2_HOST }} '
            cd /home/ec2-user/app
            git fetch origin
            git reset --hard origin/main
            
            # Run the deploy script
            ./deploy.sh
          '
